name: mkpv
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  args: 
  watcher: ^1.0.1
  markdown: 
  mkpv_socket:
    path: ../mkpv_socket/
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
