name: flutter_mkpv
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.3
  cupertino_icons: ^1.0.2
  flutter_html_table: ^3.0.0-alpha.3
  scroll_to_index: 
  path_provider: ^2.0.10
  url_launcher: 
  mkpv_socket:
    path: ./mkpv_socket/
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
