name: flutter_mkpv
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_html: ^3.0.0-alpha.3
  flutter_html_table: ^3.0.0-alpha.3
  markdown: 

  scroll_to_index: 
  path_provider: ^2.0.10
  url_launcher: 
  mkpv_socket:
    path: ./mkpv_socket/
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons_maker: "^0.10.1"
  flutter_lints: ^2.0.0


flutter_icons:
  image_path: 'assets/icon.png'
  android: false,
  ios: false,
  windows: true
  macos: true
  linux: true
flutter:
  uses-material-design: true
  assets:
    - 'assets/icon.png'
